version: '3.10'

services:
  recruiterapp:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # environment:
    #   - EMAIL_ID=changeme
    #   - EMAIL_PW=changeme
    #   - DB_HOST=db
    #   - DB_NAME=devdb
    #   - DB_USER=devuser
    #   - DB_PASS=changeme
    volumes:
      - ./recruiterapp:/recruiterapp
    command:  >
      sh -c "python manage.py makemigrations &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword

volumes:
  dev-db-data:
