version: '3.10'

services:
  recruiterapp:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    environment:
      - EMAIL_ID=${EMAIL_ID}
      - EMAIL_PW=${EMAIL_PW}
      - EMAIL_PORT=${EMAIL_PORT}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    # env_file:
    #   - .env
    volumes:
      - ./recruiterapp:/recruiterapp
    command:  >
      sh -c "python manage.py makemigrations &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    # env_file:
    #   - .env
    ports:
      - "5433:5432"
    

volumes:
  dev-db-data:
  dev-db-data2:
