version: '3.10'

services:
  recruiterapp:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./recruiterapp:/recruiterapp
    command:  >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
