# Generated by Django 4.1.4 on 2022-12-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='Initial description', max_length=254),
        ),
    ]
