# Generated by Django 4.1.4 on 2022-12-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyemployer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
