name: Tests runner

on:
  push:
    branches: [ main ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Secrets file
        run: 'echo ${{secrets.EMAIL_ID}} >> .env'
        run: 'echo ${{secrets.EMAIL_PW}} >> .env'
        run: 'echo ${{secrets.EMAIL_PORT}} >> .env'
        run: 'echo ${{secrets.DB_HOST}} >> .env'
        run: 'echo ${{secrets.DB_NAME}} >> .env'
        run: 'echo ${{secrets.DB_USER}} >> .env'
        run: 'echo ${{secrets.DB_PASS}} >> .env'
        run: 'echo ${{secrets.DJANGO_SECRET_KEY}} >> .env'
        # env:
        #   EMAIL_ID: ${{secrets.EMAIL_ID}}
        #   EMAIL_PW: ${{secrets.EMAIL_PW}}
        #   EMAIL_PORT: ${{secrets.EMAIL_PORT}}
        #   DB_HOST: ${{secrets.DB_HOST}}
        #   DB_NAME: ${{secrets.DB_NAME}}
        #   DB_USER: ${{secrets.DB_USER}}
        #   DB_PASS: ${{secrets.DB_PASS}}
        #   DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
      - name: Build
        run: docker-compose build
    
      - name: Test
        run: docker-compose run --rm recruiterapp sh -c "python manage.py wait_for_db && python manage.py test"
        
      - name: Linter
        run: docker-compose run --rm recruiterapp sh -c "flake8"
